export { default as Landing } from './landing/landing.page';
export { default as Pricing } from './pricing/pricing.pages';
export { default as Waitlist } from './waitlist/waitlist.page';
export { default as Solution } from './solutions/solutions.pages';
export { default as Partner } from './partner/partner.pages';
export { default as PrivacyPolicy } from './company/privacy-policy.pages';
export { default as TermsOfServices } from './company/terms-of-services.pages';
export { default as Blogs } from './blogs/blogs.pages';
export { default as BlogViewer } from './blogs/view/blog-view.pages';